[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "2b0cef6248c034e0b4dbabce3a8dadeabaae95f3"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "2e76b8ba5b6f1b559331a6160af4beafe05a1529e909b010971e21d62b05b9ad"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-x86_64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "1fe4cb345a9e305a8a84d783d3f18f18cdec4cfa"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "f93aff1347c3d14b20134d38b4474a933920a9eb4173c046e9e6b2d49453343d"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-aarch64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f42b2301a6f0434fcb58fe3c09713597a5ccd485"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "4ecca195db99b4db5b4f4b6336dd9fb65d39428dc6173f02c66887cebd145378"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-armv7l-linux-gnueabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "2b0cef6248c034e0b4dbabce3a8dadeabaae95f3"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "7c5ae9facbebd7508f355ab8b266986af9c23e5283317e7a07142d7fe318767e"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-x86_64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "1fe4cb345a9e305a8a84d783d3f18f18cdec4cfa"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "3b9027c69911b2513e1afb0a27c8fd45d2961ea4dbf352fdc37a62c3418461d8"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-aarch64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f42b2301a6f0434fcb58fe3c09713597a5ccd485"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "622114cc4e37d98f4630e7c1ba0238f9b95f11f263a71fb8abcdf364aab2af43"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-armv7l-linux-musleabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "b1c9dd344ec8db92b611d64b2ab89eadea734ee1"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "e3c28119cbee6ab9f158b0a55d7bd6bb1e646fe33a4dd9b25277a43670f1aee9"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-x86_64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "5cc2adcf04cfd11e67227ef9e0b99ffff86cf201"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "9566f33279e7928a839016511ec232c7ea8575360046fe30769fc973f40281e4"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-aarch64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "i686"
git-tree-sha1 = "d2785c707cb7f3aefdfbfc34ca682c803f559a68"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "78e034b3cf3d83ea6ddea73c1de82408dc8ea0a3928720affeac059afb0b79bc"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-i686-w64-mingw32.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "f12950589d28aa1bffae1ac3ca565c952b241ec7"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "267d261db330fe8708568c88d09de5f4b5c6544dd030a64e26f0989a4322c955"
    url = "https://github.com/anke1460/ElectronBuilder/releases/download/v36.1.0%2B0/ElectronJS-36.1.0+0-x86_64-w64-mingw32.tar.gz"
